/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDien;

import java.text.DecimalFormat;
import Data.DatabaseAcc;
import Model.Grade;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class QLDiem extends javax.swing.JFrame {

    /**
     * Creates new form QLDiem
     */
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Grade grade;
    int pos = 0;

    public QLDiem() {
        initComponents();
        txtHoTenSV.setEditable(true);
        txtMaSV.setEditable(true);
        txtDiemTB.setEditable(false);
        showTable();
    }

    public ResultSet find(String s) {
        try {
            // TODO add your handling code here:
            con = DatabaseAcc.getDatabaseAcc();
            pst = con.prepareStatement("SELECT * FROM SinhVien WHERE MaSV = ?");
            pst.setString(1, s);
            rs = pst.executeQuery();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        return rs;
    }

    public boolean CheckInput() {
        if (txtMaSV.getText() == null || txtHoTenSV.getText() == null) {
            return false;
        } else {
            try {
                Double.parseDouble(txtTiengAnh.getText());
                Double.parseDouble(txtTinHoc.getText());
                Double.parseDouble(txtGiaoDucTC.getText());
                return true;
            } catch (Exception E) {
                return false;
            }
        }
    }

    public ArrayList<Grade> getGradeList() {
        ArrayList<Grade> grades = new ArrayList<Grade>();
        con = DatabaseAcc.getDatabaseAcc();
        String query = "SELECT * FROM grade  ";
        try {
            st = con.createStatement();
            rs = st.executeQuery(query);
            while (rs.next()) {
                grade = new Grade(rs.getInt("id"), rs.getString("MaSV"), rs.getString("HoTenSV"),
                        Double.parseDouble(rs.getString("TiengAnh")), Double.parseDouble(rs.getString("TinHoc")),
                        Double.parseDouble(rs.getString("GDTC")), Double.parseDouble(rs.getString("DiemTB")));
                grades.add(grade);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLSV.class.getName()).log(Level.SEVERE, null, ex);
        }
        return grades;
    }

    public void showTable() {
        DefaultTableModel model = (DefaultTableModel) tbhienthi.getModel();
        model.setRowCount(0);

        try {
            con = DatabaseAcc.getDatabaseAcc();
            pst = con.prepareStatement("SELECT * FROM grade");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String maSV = rs.getString("MaSV");
                String hoTenSV = rs.getString("HoTenSV");
                double tiengAnh = rs.getDouble("TiengAnh");
                double tinHoc = rs.getDouble("TinHoc");
                double gdtc = rs.getDouble("GDTC");
                double diemTB = rs.getDouble("DiemTB");

                Object[] row = new Object[] { maSV, hoTenSV, tiengAnh, tinHoc, gdtc, diemTB };
                model.addRow(row);
            }

            rs.close();
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void ShowItem(int index) {
        txtMaSV.setText(getGradeList().get(index).getMaSV());
        txtHoTenSV.setText(getGradeList().get(index).getHoTenSV());
        txtTiengAnh.setText(Double.toString(getGradeList().get(index).getTiengAnh()));
        txtTinHoc.setText(Double.toString(getGradeList().get(index).getTinHoc()));
        txtGiaoDucTC.setText(Double.toString(getGradeList().get(index).getGDTC()));
        txtDiemTB.setText(Double.toString(getGradeList().get(index).getDiemTB()));
    }

    public void Clead() {
        txtMaSV.setText("");
        txtHoTenSV.setText("");
        txtTiengAnh.setText("");
        txtTinHoc.setText("");
        txtGiaoDucTC.setText("");
        txtDiemTB.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTKMSV = new javax.swing.JTextField();
        bntsearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTiengAnh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTinHoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGiaoDucTC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDiemTB = new javax.swing.JTextField();
        txtHoTenSV = new javax.swing.JTextField();
        bntNew = new javax.swing.JButton();
        bntSave = new javax.swing.JButton();
        bntdelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bntfirst = new javax.swing.JButton();
        bntnext = new javax.swing.JButton();
        bntprevious = new javax.swing.JButton();
        bntlast = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbhienthi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Điểm");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Quản Lý Điểm Sinh Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mã SV:");

        txtTKMSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTKMSVActionPerformed(evt);
            }
        });

        bntsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_search.png"))); // NOI18N
        bntsearch.setText("Search");
        bntsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntsearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tìm Kiếm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(44, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtTKMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 209,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bntsearch)))
                                .addGap(24, 24, 24)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtTKMSV, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bntsearch))
                                .addContainerGap(22, Short.MAX_VALUE)));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Họ Tên SV:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mã SV:");

        txtMaSV.setForeground(new java.awt.Color(51, 0, 255));
        txtMaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSVActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tiếng Anh:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Tin Học:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Giáo dục TC:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Điểm TB:");

        txtDiemTB.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtDiemTB.setForeground(new java.awt.Color(51, 0, 255));
        txtDiemTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDiemTBMouseClicked(evt);
            }
        });
        txtDiemTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemTBActionPerformed(evt);
            }
        });

        txtHoTenSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtTinHoc)
                                                        .addComponent(txtTiengAnh)
                                                        .addComponent(txtGiaoDucTC))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(jLabel9,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                56,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(42, 42, 42))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(txtDiemTB,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                107,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(txtHoTenSV,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 165,
                                                                Short.MAX_VALUE)
                                                        .addComponent(txtMaSV,
                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(0, 0, Short.MAX_VALUE)))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtHoTenSV, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(txtTiengAnh,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(txtTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(txtGiaoDucTC,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(19, Short.MAX_VALUE)));

        bntNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_add.png"))); // NOI18N
        bntNew.setText("New");
        bntNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNewActionPerformed(evt);
            }
        });

        bntSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_save.png"))); // NOI18N
        bntSave.setText("Save");
        bntSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSaveActionPerformed(evt);
            }
        });

        bntdelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bntdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/btn_delete.png"))); // NOI18N
        bntdelete.setText("Delete");
        bntdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdeleteActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bntfirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon10.png"))); // NOI18N
        bntfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntfirstActionPerformed(evt);
            }
        });

        bntnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon7.png"))); // NOI18N
        bntnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntnextActionPerformed(evt);
            }
        });

        bntprevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon8.png"))); // NOI18N
        bntprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntpreviousActionPerformed(evt);
            }
        });

        bntlast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon9.png"))); // NOI18N
        bntlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntlastActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("BẢNG ĐIỂM SINH VIÊN");

        tbhienthi.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Mã SV", "Họ Tên", "Tiếng Anh", "Tin Học", "Giáo Dục TC", "Điểm TB"
                }));
        tbhienthi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhienthiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbhienthi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(65, 65, 65)
                                                                .addComponent(bntfirst,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(58, 58, 58)
                                                                .addComponent(bntnext,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(49, 49, 49)
                                                                .addComponent(bntprevious,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(50, 50, 50)
                                                                .addComponent(bntlast,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(38, 38, 38)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(bntSave,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                94,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(bntNew,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                94,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(bntdelete,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                94,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButton1)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(225, 225, 225)
                                                                .addComponent(jLabel10))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(171, 171, 171)
                                                .addComponent(jLabel1)))
                                .addContainerGap(31, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(jLabel1)
                                                .addGap(31, 31, 31)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(bntSave,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(36, 36, 36)
                                                                .addComponent(bntdelete,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(40, 40, 40)
                                                                .addComponent(jButton1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(bntprevious,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(bntlast,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(bntnext,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(bntfirst, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addComponent(bntNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(12, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // @by Nguyen Hai Thanh

    private void bntsearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bntsearchActionPerformed
        String maSV = txtTKMSV.getText();
        try {
            con = DatabaseAcc.getDatabaseAcc();
            pst = con.prepareStatement("SELECT * FROM grade WHERE MaSV = ?");
            pst.setString(1, maSV);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String hoTenSV = rs.getString("HoTenSV");
                double tiengAnh = rs.getDouble("TiengAnh");
                double tinHoc = rs.getDouble("TinHoc");
                double gdtc = rs.getDouble("GDTC");
                double diemTB = rs.getDouble("DiemTB");

                // Hiển thị thông tin sinh viên
                JOptionPane.showMessageDialog(this, "Đã tìm thấy sinh viên có mã: " + maSV);

                txtMaSV.setText(maSV);
                txtHoTenSV.setText(hoTenSV);
                txtTiengAnh.setText(String.valueOf(tiengAnh));
                txtTinHoc.setText(String.valueOf(tinHoc));
                txtGiaoDucTC.setText(String.valueOf(gdtc));
                txtDiemTB.setText(String.valueOf(diemTB));
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sinh viên");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu");
        }
    }// GEN-LAST:event_bntsearchActionPerformed
    // @by Nguyen Hai Thanh

    private void bntSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bntSaveActionPerformed
        if (CheckInput()) {
            String maSV = txtMaSV.getText();
            String hoTenSV = txtHoTenSV.getText();
            double tiengAnh = Double.parseDouble(txtTiengAnh.getText());
            double tinHoc = Double.parseDouble(txtTinHoc.getText());
            double gdtc = Double.parseDouble(txtGiaoDucTC.getText());

            if (tiengAnh >= 0 && tiengAnh <= 10 && tinHoc >= 0 && tinHoc <= 10 && gdtc >= 0 && gdtc <= 10) {
                double diemTB = (tiengAnh + tinHoc + gdtc) / 3;
                DecimalFormat decimalFormat = new DecimalFormat("#.##");
                String diemTBFormatted = decimalFormat.format(diemTB);

                txtDiemTB.setText(diemTBFormatted);

                if (!maSV.isEmpty() && !hoTenSV.isEmpty()) {
                    try {
                        con = DatabaseAcc.getDatabaseAcc();

                        // Kiểm tra xem mã sinh viên đã tồn tại trong cơ sở dữ liệu hay chưa
                        PreparedStatement checkStatement = con.prepareStatement("SELECT * FROM grade WHERE MaSV = ?");
                        checkStatement.setString(1, maSV);
                        ResultSet checkResult = checkStatement.executeQuery();

                        if (checkResult.next()) {
                            JOptionPane.showMessageDialog(this, "Mã sinh viên đã tồn tại trong cơ sở dữ liệu");
                        } else {
                            // Mã sinh viên không tồn tại, thêm sinh viên vào cơ sở dữ liệu
                            pst = con.prepareStatement(
                                    "INSERT INTO grade(MaSV, HoTenSV, TiengAnh, TinHoc, GDTC, DiemTB) VALUES (?, ?, ?, ?, ?, ?)");
                            pst.setString(1, maSV);
                            pst.setString(2, hoTenSV);
                            pst.setDouble(3, tiengAnh);
                            pst.setDouble(4, tinHoc);
                            pst.setDouble(5, gdtc);
                            pst.setDouble(6, diemTB);
                            pst.executeUpdate();

                            JOptionPane.showMessageDialog(this, "Thêm thành công");
                            this.Clead();
                            showTable();
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Mã sinh viên và họ tên không được để trống");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Điểm không hợp lệ. Vui lòng nhập điểm từ 0 đến 10");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Thêm không thành công");
            this.Clead();
        }
    }// GEN-LAST:event_bntSaveActionPerformed
    // @by Nguyen Hai Thanh

    private void txtDiemTBMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_txtDiemTBMouseClicked
        // TODO add your handling code here:
        double tiengAnh = Double.parseDouble(txtTiengAnh.getText());
        double tinHoc = Double.parseDouble(txtTinHoc.getText());
        double gdtc = Double.parseDouble(txtGiaoDucTC.getText());
        double diemTB = (tiengAnh + tinHoc + gdtc) / 3;

        DecimalFormat decimalFormat = new DecimalFormat("#.##");
        String diemTBFormatted = decimalFormat.format(diemTB);

        txtDiemTB.setText(diemTBFormatted);
    }// GEN-LAST:event_txtDiemTBMouseClicked
    // @by Nguyen Hai Thanh

    private void bntdeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bntdeleteActionPerformed

        if (!txtMaSV.getText().equals("")) {
            String maSV = txtMaSV.getText();
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa " + maSV + "?", "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    con = DatabaseAcc.getDatabaseAcc();
                    pst = con.prepareStatement("DELETE FROM grade WHERE MaSV = ?");
                    pst.setString(1, maSV);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    showTable();
                } catch (SQLException ex) {
                    Logger.getLogger(QLDiem.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Xóa không thành công");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui Lòng chọn sinh viên cần xóa trong bảng !");
        }
    }// GEN-LAST:event_bntdeleteActionPerformed

    private void tbhienthiMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tbhienthiMouseClicked
        // TODO add your handling code here:
        int index = tbhienthi.getSelectedRow();
        ShowItem(index);
    }// GEN-LAST:event_tbhienthiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (CheckInput()) {
            String maSV = txtMaSV.getText();
            String hoTenSV = txtHoTenSV.getText();
            double tiengAnh = Double.parseDouble(txtTiengAnh.getText());
            double tinHoc = Double.parseDouble(txtTinHoc.getText());
            double gdtc = Double.parseDouble(txtGiaoDucTC.getText());

            // Kiểm tra điểm các môn học không vượt quá 10
            if (tiengAnh <= 10 && tinHoc <= 10 && gdtc <= 10) {
                try {
                    con = DatabaseAcc.getDatabaseAcc();

                    // Kiểm tra xem mã sinh viên đã nhập có khớp với mã sinh viên hiện tại hay không
                    String selectString = "SELECT MaSV FROM grade WHERE MaSV = ?";
                    pst = con.prepareStatement(selectString);
                    pst.setString(1, maSV);
                    ResultSet rs = pst.executeQuery();
                    if (rs.next()) {
                        // Mã sinh viên khớp, thực hiện cập nhật dữ liệu
                        String updateString = "UPDATE grade SET HoTenSV = ?, TiengAnh = ?, TinHoc = ?, GDTC = ?, DiemTB = ? WHERE MaSV = ?";
                        pst = con.prepareStatement(updateString);
                        pst.setString(1, hoTenSV);
                        pst.setDouble(2, tiengAnh);
                        pst.setDouble(3, tinHoc);
                        pst.setDouble(4, gdtc);
                        double diemTB = (tiengAnh + tinHoc + gdtc) / 3;
                        pst.setDouble(5, diemTB);
                        pst.setString(6, maSV);
                        pst.executeUpdate();

                        JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                        this.Clead();
                        showTable();
                    } else {
                        // Mã sinh viên không khớp, hiển thị thông báo lỗi
                        JOptionPane.showMessageDialog(this, "Mã sinh viên không tồn tại");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Điểm các môn học không được vượt quá 10");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật không thành công");
        }
    }// GEN-LAST:event_jButton1ActionPerformed
    // @by Nguyen Hai Thanh

    private void bntNewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bntNewActionPerformed
        // TODO add your handling code here:
        this.Clead();
    }// GEN-LAST:event_bntNewActionPerformed

    private void bntfirstActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bntfirstActionPerformed
        // TODO add your handling code here:
        pos = 0;
        ShowItem(pos);
    }// GEN-LAST:event_bntfirstActionPerformed

    private void bntlastActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bntlastActionPerformed
        // TODO add your handling code here:
        pos = getGradeList().size() - 1;
        ShowItem(pos);
    }// GEN-LAST:event_bntlastActionPerformed

    private void bntnextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bntnextActionPerformed
        // TODO add your handling code here:
        pos++;
        if (pos >= getGradeList().size()) {
            pos = getGradeList().size() - 1;
        }
        ShowItem(pos);
    }// GEN-LAST:event_bntnextActionPerformed
    // @by Nguyen Hai Thanh

    private void bntpreviousActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bntpreviousActionPerformed
        // TODO add your handling code here:
        pos--;
        if (pos < 0) {
            pos = 0;
        }
        ShowItem(pos);
    }// GEN-LAST:event_bntpreviousActionPerformed

    private void txtTKMSVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTKMSVActionPerformed
        // TODO add your handling code here:
        String maSV = txtTKMSV.getText();

    }// GEN-LAST:event_txtTKMSVActionPerformed

    private void txtMaSVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMaSVActionPerformed
        // TODO add your handling code here

        String maSV = txtMaSV.getText();
    }// GEN-LAST:event_txtMaSVActionPerformed
    // @by Nguyen Hai Thanh

    private void txtHoTenSVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtHoTenSVActionPerformed
        // TODO add your handling code here:
        String hoTenSV = txtHoTenSV.getText();
    }// GEN-LAST:event_txtHoTenSVActionPerformed

    private void txtDiemTBActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDiemTBActionPerformed
        // TODO add your handling code here:
        double tiengAnh = Double.parseDouble(txtTiengAnh.getText());
        double tinHoc = Double.parseDouble(txtTinHoc.getText());
        double gdtc = Double.parseDouble(txtGiaoDucTC.getText());
        double diemTB = (tiengAnh + tinHoc + gdtc) / 3;
        DecimalFormat decimalFormat = new DecimalFormat("#.##");
        String diemTBFormatted = decimalFormat.format(diemTB);

        txtDiemTB.setText(diemTBFormatted);
    }// GEN-LAST:event_txtDiemTBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDiem().setVisible(true);
            }
        });
    }

    // @by Nguyen Hai Thanh
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntNew;
    private javax.swing.JButton bntSave;
    private javax.swing.JButton bntdelete;
    private javax.swing.JButton bntfirst;
    private javax.swing.JButton bntlast;
    private javax.swing.JButton bntnext;
    private javax.swing.JButton bntprevious;
    private javax.swing.JButton bntsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbhienthi;
    private javax.swing.JTextField txtDiemTB;
    private javax.swing.JTextField txtGiaoDucTC;
    private javax.swing.JTextField txtHoTenSV;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtTKMSV;
    private javax.swing.JTextField txtTiengAnh;
    private javax.swing.JTextField txtTinHoc;
    // End of variables declaration//GEN-END:variables

    boolean them(String maSV, String hoTenSV, double tiengAnh, double tinHoc, double gdtc) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
// @by Nguyen Hai Thanh